on:
   release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: cd ./src && npm install && cd ..
      - run: cd ./src && npm version ${GITHUB_REF##*/} && cd ..
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: "./src/package.json"
          token: ${{ secrets.NPM_TOKEN }}